### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by 84m** [Haehnchen/idea-php-shopware-plugin#16]
```Do not call synchronous refresh under read lock (except from EDT) - this will cause a deadlock if there are any events to fire.```

//cc @mitelg

**Comment by mitelg** [comment]
thanks @84m 
that is the only problem I had so far. 
all other new features are awesome @84m @Haehnchen @florianklockenkemper :+1:

**Comment by Haehnchen** [comment]
@84m, @mitelg can you provide a full stacktrace?

**Comment by mitelg** [comment]
@Haehnchen I will try to remember to copy it the next time :smiley:

**Comment by mitelg** [comment]
Hi, the error just occured on my PHPstorm:


> Do not call synchronous refresh under read lock (except from EDT) - this will cause a deadlock if there are any events to fire.
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:62)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:104)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processSingleEvent(RefreshQueueImpl.java:143)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:244)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:92)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:251)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:138)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:73)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByIoFile(LocalFileSystemBase.java:246)
	at com.intellij.openapi.vfs.VfsUtil.findFileByIoFile(VfsUtil.java:234)
	at de.espend.idea.shopware.types.ShopwareMagicMethodTypeProvider.getBySignature(ShopwareMagicMethodTypeProvider.java:80)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:418)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:449)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:393)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:81)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.globalLocationAware(PhpType.java:404)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:154)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:107)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:104)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:99)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:85)
	at de.espend.idea.shopware.util.dict.PsiParameterStorageRunnable$MyPsiRecursiveElementWalkingVisitor.visitMethodReference(PsiParameterStorageRunnable.java:61)
	at de.espend.idea.shopware.util.dict.PsiParameterStorageRunnable$MyPsiRecursiveElementWalkingVisitor.visitElement(PsiParameterStorageRunnable.java:48)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:64)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:26)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at de.espend.idea.shopware.util.dict.PsiParameterStorageRunnable$MyPsiRecursiveElementWalkingVisitor.visitElement(PsiParameterStorageRunnable.java:50)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:28)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
	at de.espend.idea.shopware.util.dict.PsiParameterStorageRunnable.run(PsiParameterStorageRunnable.java:40)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at de.espend.idea.shopware.ShopwareProjectComponent$1$1.run(ShopwareProjectComponent.java:89)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by Haehnchen** [comment]
related to #15
