### ISSUE TITLE
PHPStorm 10 EAP

### ISSUE THREAD

**Issue by jochenmanz** [Haehnchen/idea-php-shopware-plugin#20]
Hallo,

i just got the following Exception:

com.jetbrains.php.lang.psi.PhpPsiUtil.isOfType(Lcom/intellij/psi/PsiElement;Lcom/intellij/psi/tree/IElementType;)Z

**Comment by Haehnchen** [comment]
please whenever possible add a full stacktrace.

**Comment by mitelg** [comment]
Hi Daniel,
got that error, too. Here is the full stack trace
```
com.jetbrains.php.lang.psi.PhpPsiUtil.isOfType(Lcom/intellij/psi/PsiElement;Lcom/intellij/psi/tree/IElementType;)Z
java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.PhpPsiUtil.isOfType(Lcom/intellij/psi/PsiElement;Lcom/intellij/psi/tree/IElementType;)Z
	at de.espend.idea.shopware.reference.EventSubscriberReferenceContributor$6.getReferencesByElement(EventSubscriberReferenceContributor.java:220)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:66)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:60)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:283)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by janbuecker** [comment]
Problem still exists in final version 10.0.1.

**Comment by mitelg** [comment]
the problem is still there in version 10.0.3
is there a chance, that you will fix this issue @Haehnchen ? :blush:

**Comment by Haehnchen** [comment]
expect a fix this week :sunglasses:

**Comment by mitelg** [comment]
:+1: :+1:

**Comment by Haehnchen** [comment]
@mitelg mhh... function never removed,  nevertheless i replaced it and also build against newest PHP Plugin. please some feedback

**Comment by bcremer** [comment]
@Haehnchen `1.7.2` release works fine for me. Thank you very much :+1:

**Comment by mitelg** [comment]
@Haehnchen jep, everything fine again! thanks a lot! :+1:
