### ISSUE TITLE
Create Method on subscribeEvent

### ISSUE THREAD

**Issue by shyim** [Haehnchen/idea-php-shopware-plugin#21]
Phpstorm has on ALT + Enter a Shortcut to create methods. When i use it on a subscribeEvent Method, i will get a Exception:

Stacktrace:
com.jetbrains.php.codeInsight.PhpCodeInsightUtil.collectNamespaces(Lcom/jetbrains/php/lang/psi/PhpFile;)Ljava/util/List;
java.lang.NoSuchMethodError: com.jetbrains.php.codeInsight.PhpCodeInsightUtil.collectNamespaces(Lcom/jetbrains/php/lang/psi/PhpFile;)Ljava/util/List;
	at de.espend.idea.shopware.inspection.quickfix.CreateMethodQuickFix.applyFix(CreateMethodQuickFix.java:82)
	at de.espend.idea.shopware.inspection.quickfix.CreateMethodQuickFix.applyFix(CreateMethodQuickFix.java:42)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:86)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$2.run(ShowIntentionActionsHandler.java:188)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$3.run(ShowIntentionActionsHandler.java:202)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:207)
	at com.intellij.codeInsight.intention.impl.IntentionListStep$2$1.run(IntentionListStep.java:260)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Tried code:
$this->subscribeEvent(
            'Enlight_Controller_Action_PostDispatchSecure_Frontend',
            'onPostDispatch'
        );

![bildschirmfoto 2015-11-06 um 19 28 49](https://cloud.githubusercontent.com/assets/6224096/11005174/aaca7cd6-84bc-11e5-8efe-a045beb3780a.png)

**Comment by Haehnchen** [comment]
PhpStorm 10 issue, related #20

**Comment by Haehnchen** [comment]
@shyim please check out latest release `1.7.2`

**Comment by bcremer** [comment]
Can confirm it works with `1.7.2` again. Thank you @Haehnchen  :+1:

**Comment by shyim** [comment]
Thank you @Haehnchen  :+1:
