### ISSUE TITLE
Worker exited due to exception

### ISSUE THREAD

**Issue by mitelg** [Haehnchen/idea-php-shopware-plugin#41]
Hi @Haehnchen 
I got this error today:

> java.lang.NullPointerException
	at de.espend.idea.shopware.reference.LazySubscriberReferenceProvider.getGotoDeclarationTargets(LazySubscriberReferenceProvider.java:257)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:278)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:536)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:515)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2400(CtrlMouseHandler.java:106)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:844)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3000(CtrlMouseHandler.java:784)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:829)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:870)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:187)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:211)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

PhpStorm 2016.2
Build #PS-162.1121.38, built on July 12, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by mrbrazzi** [comment]
Hi, I got the same error today. PHPStorm 2016.2.1 show this error: "Worker exited due to exception"

I have Shopware Plugin v2.2.2.

See image for more details.
![phpstorm-2016 2 1-error-shopware-plugin](https://cloud.githubusercontent.com/assets/1132397/18013113/ae66d4e2-6b8a-11e6-934d-e1e7e9c3c879.jpg)

Thanks in advance.

**Comment by Haehnchen** [comment]
done
