### ISSUE TITLE
Icon cannot be found

### ISSUE THREAD

**Issue by shyim** [Haehnchen/idea-php-shopware-plugin#74]
PhpStorm reports me a error with the extension
Message
```
java.lang.Throwable: Icon cannot be found in 'icons/shopware.png', aClass='class de.espend.idea.shopware.ShopwarePluginIcons'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:109)
	at de.espend.idea.shopware.ShopwarePluginIcons.<clinit>(ShopwarePluginIcons.java:11)
	at de.espend.idea.shopware.navigation.SmartyTemplateLineMarkerProvider.getRelatedPopover(SmartyTemplateLineMarkerProvider.java:117)
	at de.espend.idea.shopware.navigation.SmartyTemplateLineMarkerProvider.attachFileContextMaker(SmartyTemplateLineMarkerProvider.java:100)
	at de.espend.idea.shopware.navigation.SmartyTemplateLineMarkerProvider.collectSlowLineMarkers(SmartyTemplateLineMarkerProvider.java:61)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:197)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by shyim** [comment]
Das gleiche kommt auch mit den Symfony Plugin

**Comment by cedricziel** [comment]
Should be fixed with 3.0 - please re-open if not.
