### ISSUE TITLE
Exception on Start-Up PhpStorm 2018.3.1 and Shopware plugin v3.1

### ISSUE THREAD

**Issue by mitelg** [Haehnchen/idea-php-shopware-plugin#89]
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:773)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:722)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:894)
	at com.intellij.util.indexing.FileBasedIndexImpl.collectFileIdsContainingAllKeys(FileBasedIndexImpl.java:1119)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:982)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1155)
	at de.espend.idea.shopware.ShopwareProjectComponent$1.lambda$run$1(ShopwareProjectComponent.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:948)
	at de.espend.idea.shopware.ShopwareProjectComponent$1.run(ShopwareProjectComponent.java:65)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by mitelg** [comment]
still an issue with PhpStorm 2018.3.5 :blush:

**Comment by mitelg** [comment]
hey @Haehnchen 
I still got this error once in a while with PhpStorm 2019.1.2
Is there any chance that you will fix this issue? :see_no_evil:

**Comment by Haehnchen** [comment]
done via 4.1.1 also added here to the 3.x code
